### ISSUE TITLE
Hola, ¿se podría añadir un archivo de configuración?

### ISSUE THREAD

**Issue by gaspect** [apiad/illiterate#3]
Hola, primero quiciera dar gracias por la herramienta, es muy útil. También quiciera proponer una pequeña característica (si estan aceptando este tipo de retroalimentación claro).
 **Sería que el comando *illiterate* corra siguiendo una archivo de configuración si es que este existe.**
## Ahora explico a que se debe. 
Hace unos meses empecé a hacer un proyecto pequeño pero que tenía varias partes privadas y alguna que otra documentación extra que no estaba embebida en el código y cada vez que tenía que correr el comando era realmente un incordio navegar por 60 archivos de documentación cuando realmente quería exponer la documentación de alrededor de 20 archivos (que al final se lograba configurando la navegación de mkdocs). Además de que tenía que añadir 6 archivos extra con el comando *copy* . Para este tipo de proyecto sería mas útil (a mi entender) un archivito de configuración donde pongan todo eso de una vez y ya.
## PD: 
Estaba revisando el proyecto de autogoal los otros días (pura curiosidad) y vi que esta característica también les seria útil a ustedes a la hora de documentar ese proyecto (es  grande y tiene varios modulos privados que seguro comentan pero no exponen la documentación). Salu2s y disculpen la molestia.
> Disculpen por el título tan malo del issue :neutral_face:

**Comment by gaspect** [comment]
Añadir un método como este en illiterate/\_\_init\_\_.py sería la idea:

```python
# ### Processing files defined in .cfg file

# We are going to use the configparser module to achieve this

import configparser

def process_from_cfg(cfg_file:Path):
    if cfg_file.exists():
        cfg  = configparser.ConfigParser()
        cfg.read(cfg_file)
        output_folder = cfg['BASIC']['output_folder']
        inline = cfg['BASIC']['inline']
        for key, value in cfg['INCLUDE']:
           # the key is the output name the value will be the name source file
            output_path = output_folder / ".".join(key.with_suffix(".md").parts)
            process_one(value, output_path, inline)
    else:
        # TODO
        pass
```
Después integrarlo al punto de entrada, que no se como quedaría mejor hacer eso, hay varias variantes

**Comment by apiad** [comment]
A mi me parece genial! Creo que preferiría un archivo en YAML que en CFG, pero eso es gusto personal. 

Te embullas a hacer un PR?

**Comment by gaspect** [comment]
Entonces con yaml me gustaría compartir primero la idea antes de lanzarme.

Si el comando `python -m illiterate` es llamado sin argumentos buscaría en el directorio donde fue llamado un archivo **illiterate.yml** y cargaría la configuración de ahí , en caso de no encontrarlo imprimiría en pantalla la ayuda del comando + como configurarlo .

El archivo **illiterate.yml** tendría la siguiente forma:


```yml
inline: "para cubrir el comando inline"
output: "nombre del directorio de salida"

# esto que sigue  cubriría también los archivos que usualmente se pasan por el comando 'copy'

sources:
  <nombre del archivo de salida >:< nombre del archivo fuente >
```

Además habría que añadir el paquete pyyaml como dependencia.

No sé si habría que añadir algo más .

**Comment by apiad** [comment]
Closed by #4
