### ISSUE TITLE
Error a la hora de procesar los archivos de configuración

### ISSUE THREAD

**Issue by gaspect** [apiad/illiterate#5]
El comando `illiterate preset build` falla parcialmente. Estoy en ello.

**Comment by gaspect** [comment]
Ya está resuelto aquí #6, ayer me había encontrado con ese problema cuando probaba la solución y me hice la idea de que lo había arreglado y hoy instalé el programa directo desde aquí y me di cuenta que no fue así.

**Comment by apiad** [comment]
Closed by #6
